### PR TITLE
force to use opus

### PR DESCRIPTION
**Pull request by sakkuru**
* In audio sending, it force to use opus

### CODE REVIEW

**Comment by KensakuKOMATSU** [comment]
thx PR

it seems nice. However, I guess it will be better to create separate library for this forcing feature, since it will be easier for testing.

Also, I wanna make environment variable to enable this feature. 

For instance,

```
$ FORCE_OPUS=yes node app.js
```

In this way, I'll update this PR.

**Comment by KensakuKOMATSU** [comment]
@sakkuru request for review.

I tweaked your PR as described in previous comment.

signaling_controller.js : check FORCE_OPUS env. when it is true, sdp.force_opus will be called
miscs/sdp.js : implement force_opus feature
test/unit/sdp.test.js : create unit test code for SDP#force_opus()
readme.md : append explanation of FORCE_OPUS. it will enable forcing opus codec.

Since I merged current master branch code, please ignore other changed files.

**Comment by sakkuru** [comment]
LGTM!!

**Comment by KensakuKOMATSU** [comment]
I'll close this PR. Since other branch is for this feature.

**Pull request merged**
